name: soft_plc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  get_it: ^7.6.4
  mqtt_client: ^10.0.0
  sqlite3: ^2.1.0
  typed_data: ^1.3.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
